### ISSUE TITLE
Merging Dependabot Alerts

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/seedtool.info#7]
@Sjlver, when we see Dependabot alerts (like https://github.com/BlockchainCommons/seedtool.info/pull/6) should we update them? Or ping you first?

**Comment by Sjlver** [comment]
Feel free to simply merge.

In general, I'm happy to do code reviews for other people's contributions, and also happy to have my code reviewed if someone wants to. That said, automatic commits like #6 are completely uncontroversial and can be merged without letting me know.

I have a preference for using "rebase and merge" rather than creating a merge commit, where possible, because that creates a linear Git history.
